- name: Deploy Website on CentOS
  hosts: all
  become: yes
  tasks:
    - name: Install Apache
      dnf:
        name: httpd
        state: present

    - name: Start and Enable Apache
      systemd:
        name: httpd
        state: started
        enabled: yes

    - name: Copy Website Files
      copy:
        src: /ansible/oxer-html
        dest: /var/www/html/
        owner: apache
        group: apache
        mode: '0755'

    - name: Open HTTP Port (80)
      firewalld:
        service: http
        permanent: yes
        state: enabled
        immediate: yes

    - name: Restart Apache to Apply Changes
      systemd:
        name: httpd
        state: restarted
